name: main
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install packages
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn install --frozen-lockfile --silent
    - name: Build page
      run: yarn build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist